"""add_images_to_messages

Revision ID: 4a3e80dc6c45
Revises: 4c1c9d64ca09
Create Date: 2026-03-08 13:14:59.729207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3e80dc6c45'
down_revision: Union[str, Sequence[str], None] = '4c1c9d64ca09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'images')
    # ### end Alembic commands ###
