"""Add indexes on frames.conversation_id and messages.frame_id

Revision ID: 9ec2a635a335
Revises: add_think_to_agents
Create Date: 2026-02-07 01:39:13.788317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ec2a635a335'
down_revision: Union[str, Sequence[str], None] = 'add_think_to_agents'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_frames_conversation_id'), 'frames', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_frame_id'), 'messages', ['frame_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_frame_id'), table_name='messages')
    op.drop_index(op.f('ix_frames_conversation_id'), table_name='frames')
    # ### end Alembic commands ###
