"""Write `protocol/events.json` — the one place the three languages agree.

The WebSocket protocol is defined in `websocket/events.py` and was then retyped
by hand as string literals in TypeScript and again in Kotlin, with nothing
checking that the copies matched. They did not: the desktop client was sending
`compact_context`, an event its own union type did not contain (#93).

This writes the backend's definition to a manifest each client's test reads, so
a divergence fails that client's CI job instead of shipping. Run it after
touching `EventType`, the direction sets, or `WIRE_PROTOCOL`:

    python -m scripts.generate_protocol

`tests/test_protocol_manifest.py` fails if the committed file is stale, so
forgetting to run it is caught rather than assumed.
"""

from __future__ import annotations

import json
from pathlib import Path

from kurisuassistant.version import WIRE_PROTOCOL
from kurisuassistant.websocket.events import (
    BINARY_EVENTS,
    CLIENT_TO_SERVER,
    SERVER_TO_CLIENT,
    EventType,
)

MANIFEST_PATH = Path(__file__).resolve().parent.parent.parent / "protocol" / "events.json"

HEADER = (
    "Generated by backend/scripts/generate_protocol.py — do not edit by hand. "
    "The backend's websocket/events.py is the source of truth (#93)."
)


def build_manifest() -> dict:
    """The protocol as data: every event, which way it travels, how it is carried."""
    undirected = [e.value for e in EventType if e not in CLIENT_TO_SERVER | SERVER_TO_CLIENT]
    if undirected:
        raise SystemExit(
            f"these events have no direction in websocket/events.py: {sorted(undirected)}"
        )
    both = CLIENT_TO_SERVER & SERVER_TO_CLIENT
    if both:
        raise SystemExit(f"these events claim both directions: {sorted(e.value for e in both)}")

    return {
        "_comment": HEADER,
        "wire_protocol": WIRE_PROTOCOL,
        "events": {
            event.value: {
                "direction": "client_to_server" if event in CLIENT_TO_SERVER else "server_to_client",
                "transport": "binary" if event in BINARY_EVENTS else "json",
            }
            for event in sorted(EventType, key=lambda e: e.value)
        },
    }


def render() -> str:
    return json.dumps(build_manifest(), indent=2, ensure_ascii=False) + "\n"


def main() -> None:
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(render())
    print(f"wrote {MANIFEST_PATH}")


if __name__ == "__main__":
    main()
