"""add_tool_status_to_messages

Revision ID: 094c553fc149
Revises: b2c6b8273b84
Create Date: 2026-03-29 20:55:51.647311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '094c553fc149'
down_revision: Union[str, Sequence[str], None] = 'b2c6b8273b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_status')
    # ### end Alembic commands ###
