"""add_compacted_context_to_conversations

Revision ID: 4d1803f5382a
Revises: 9cda43bc12d5
Create Date: 2026-03-26 23:21:16.757459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1803f5382a'
down_revision: Union[str, Sequence[str], None] = '9cda43bc12d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('compacted_context', sa.Text(), server_default='', nullable=False))
    op.add_column('conversations', sa.Column('compacted_up_to_id', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'compacted_up_to_id')
    op.drop_column('conversations', 'compacted_context')
    # ### end Alembic commands ###
