"""add_tool_policies_to_user

Revision ID: 7038b249d1a4
Revises: 83e667457a0b
Create Date: 2026-04-13 06:14:54.008516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7038b249d1a4'
down_revision: Union[str, Sequence[str], None] = '83e667457a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tool_policies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tool_policies')
    # ### end Alembic commands ###
