"""add_thinking_field_to_messages

Revision ID: 7dd75b21ce44
Revises: cbfd2ab9dea3
Create Date: 2025-12-20 10:42:59.329897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dd75b21ce44'
down_revision: Union[str, Sequence[str], None] = 'cbfd2ab9dea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thinking', sa.Text(), nullable=True))
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'thinking')
    # ### end Alembic commands ###
