"""add_use_deferred_tools_to_agents

Revision ID: b2c6b8273b84
Revises: 4d1803f5382a
Create Date: 2026-03-29 20:02:47.777421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c6b8273b84'
down_revision: Union[str, Sequence[str], None] = '4d1803f5382a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('use_deferred_tools', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'use_deferred_tools')
    # ### end Alembic commands ###
