"""add_emotion_cues_to_messages

Where the persona's feeling changed inside an assistant message (#243):
``[{"emotion": "happy", "at": 42}, ...]``, ``at`` counted in UTF-16 code units of
``messages.message``. The tags the model wrote to say so are stripped before
anything is stored — ``message`` and ``raw_output`` both hold the clean text — so
this column is the only record of where they stood, and a reloaded conversation
can set the character's resting face from the last one. Nullable: every message
before this, every user and tool message, and every reply from a persona
without the channel has none.

Revision ID: 236f4ed54660
Revises: 3eb07d0e8d1f
Create Date: 2026-09-20 12:49:50.737272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236f4ed54660'
down_revision: Union[str, Sequence[str], None] = '3eb07d0e8d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('emotion_cues', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'emotion_cues')
    # ### end Alembic commands ###
