"""create_passages_table

The retrieval index (#6): one row per verbatim slice of a stored message or of a
readable file in Kurisu Drive, which is what the ``recall_regex`` and
``recall_semantic`` tools search. Plus the bookkeeping that keeps it in step —
``conversations.indexed_up_to_id`` / ``indexed_at`` (which messages are already
chunked) and ``drive_nodes.indexed_checksum`` (which version of a file is).

``embedding`` is a ``vector`` with no dimension on purpose: the model is the
operator's (``EMBEDDING_MODEL``) and models differ in width. pgvector cannot put
an HNSW index on such a column, so a semantic query is an exact scan over one
account's rows — fast enough at that scale, and exact. The ``vector`` extension
itself was created by ``20486507cf9d`` (face embeddings).

Every foreign key cascades: a message, conversation, file or user going away
takes its passages with it in the database, which matters because the message
and drive deletes are bulk statements that fire no ORM events.

There is no data work here. Existing conversations and files are indexed by the
background scanner after deploy (it needs the embedding service, which a
migration must not), so recall over old material fills in over the following
minutes to hours depending on how much there is.

Revision ID: 4281377948c4
Revises: 9969521565a7
Create Date: 2026-09-07 05:08:41.215182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '4281377948c4'
down_revision: Union[str, Sequence[str], None] = '9969521565a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('drive_node_id', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), server_default='0', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('embed_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['drive_node_id'], ['drive_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passages_conversation_id'), 'passages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_passages_drive_node_id'), 'passages', ['drive_node_id'], unique=False)
    op.create_index(op.f('ix_passages_message_id'), 'passages', ['message_id'], unique=False)
    op.create_index('ix_passages_pending_embed', 'passages', ['id'], unique=False, postgresql_where=sa.text('embedding IS NULL AND embed_attempts < 5'))
    op.create_index(op.f('ix_passages_user_id'), 'passages', ['user_id'], unique=False)
    op.create_index('ix_passages_user_id_embedding_model', 'passages', ['user_id', 'embedding_model'], unique=False)
    op.add_column('conversations', sa.Column('indexed_up_to_id', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversations', sa.Column('indexed_at', sa.DateTime(), nullable=True))
    op.add_column('drive_nodes', sa.Column('indexed_checksum', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drive_nodes', 'indexed_checksum')
    op.drop_column('conversations', 'indexed_at')
    op.drop_column('conversations', 'indexed_up_to_id')
    op.drop_index('ix_passages_user_id_embedding_model', table_name='passages')
    op.drop_index(op.f('ix_passages_user_id'), table_name='passages')
    op.drop_index('ix_passages_pending_embed', table_name='passages', postgresql_where=sa.text('embedding IS NULL AND embed_attempts < 5'))
    op.drop_index(op.f('ix_passages_message_id'), table_name='passages')
    op.drop_index(op.f('ix_passages_drive_node_id'), table_name='passages')
    op.drop_index(op.f('ix_passages_conversation_id'), table_name='passages')
    op.drop_table('passages')
    # ### end Alembic commands ###
