"""add_summary_provider_to_users

Revision ID: 7a8f9c7cf0af
Revises: 8945eadfca8e
Create Date: 2026-03-25 08:24:37.507377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8f9c7cf0af'
down_revision: Union[str, Sequence[str], None] = '8945eadfca8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('summary_provider', sa.String(), server_default='ollama', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'summary_provider')
    # ### end Alembic commands ###
