"""create_drive_nodes_table

Kurisu Drive: account-scoped file storage (#17). One self-referencing tree per
user; a file's bytes live under ``data/drive/{user_id}/{storage_key}`` and the
row is the handle, so this table and that directory are one unit for backup —
see ``docs/operations.md``.

Uniqueness is two *partial* indexes rather than one constraint, because Postgres
treats NULLs as distinct: a plain UNIQUE over (user_id, parent_id, name) would
happily allow two folders called "Reports" at the root, since their parent_id is
NULL both times. The pair below covers the two cases separately and doubles as
the index every folder listing reads.

Revision ID: 9969521565a7
Revises: 4022208dbec1
Create Date: 2026-09-06 11:34:49.341116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9969521565a7'
down_revision: Union[str, Sequence[str], None] = '4022208dbec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drive_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_dir', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('size', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['drive_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drive_nodes_parent_id'), 'drive_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_drive_nodes_user_id'), 'drive_nodes', ['user_id'], unique=False)
    op.create_index('uq_drive_node_user_id_name_root', 'drive_nodes', ['user_id', 'name'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    op.create_index('uq_drive_node_user_id_parent_id_name', 'drive_nodes', ['user_id', 'parent_id', 'name'], unique=True, postgresql_where=sa.text('parent_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_drive_node_user_id_parent_id_name', table_name='drive_nodes', postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.drop_index('uq_drive_node_user_id_name_root', table_name='drive_nodes', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_index(op.f('ix_drive_nodes_user_id'), table_name='drive_nodes')
    op.drop_index(op.f('ix_drive_nodes_parent_id'), table_name='drive_nodes')
    op.drop_table('drive_nodes')
    # ### end Alembic commands ###
