"""Initial migration

Revision ID: c0b02d56d7ff
Revises: 
Create Date: 2025-08-03 16:03:11.993040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b02d56d7ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _create_legacy_schema() -> None:
    """Recreate the pre-Alembic schema on an empty database.

    This revision was autogenerated against a database whose users,
    conversations and messages tables had been created by the old raw-SQL
    bootstrap (core/helpers/db.py, July 2025). It only alters those tables, so
    a fresh database has nothing to alter. Create them here exactly as the old
    bootstrap did, then let the autogenerated alterations below run as usual.
    """
    op.execute(
        """
        CREATE TABLE users (
            username TEXT PRIMARY KEY,
            password TEXT NOT NULL,
            system_prompt TEXT DEFAULT ''
        )
        """
    )
    op.execute(
        """
        CREATE TABLE conversations (
            id SERIAL PRIMARY KEY,
            username TEXT NOT NULL,
            title TEXT DEFAULT 'New conversation',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute(
        """
        CREATE TABLE messages (
            id SERIAL PRIMARY KEY,
            role TEXT NOT NULL,
            username TEXT NOT NULL,
            message TEXT NOT NULL,
            conversation_id INTEGER,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    op.execute("CREATE INDEX idx_messages_conversation_id ON messages(conversation_id)")
    op.execute("CREATE INDEX idx_messages_username ON messages(username)")


def upgrade() -> None:
    """Upgrade schema."""
    if not sa.inspect(op.get_bind()).has_table('users'):
        _create_legacy_schema()

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_foreign_key(None, 'conversations', 'users', ['username'], ['username'])
    op.alter_column('messages', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages', if_exists=True)
    op.drop_index(op.f('idx_messages_hash'), table_name='messages', if_exists=True)
    op.drop_index(op.f('idx_messages_username'), table_name='messages', if_exists=True)
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_column('messages', 'message_hash', if_exists=True)
    op.add_column('users', sa.Column('preferred_name', sa.Text(), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('users', 'preferred_name')
    op.add_column('messages', sa.Column('message_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_index(op.f('idx_messages_username'), 'messages', ['username'], unique=False)
    op.create_index(op.f('idx_messages_hash'), 'messages', ['message_hash'], unique=False)
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.alter_column('messages', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.alter_column('conversations', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
