"""add_consolidation_state_to_conversations

Memory consolidation bookkeeping on the conversation row, and an index on
``updated_at`` (#96). The idle scanner used to select every idle conversation the
user had ever finished, every minute, and remembered what it had queued only in
memory: a failure wedged a conversation until restart, and a restart forgot what
was pending. Now the row says whether it has been consolidated since it last
changed and when a failed attempt may be retried.

Backfill: every existing conversation is stamped ``consolidated_at = updated_at``,
i.e. treated as already consolidated. Nothing is lost by that — before this
revision each of them had been re-consolidated on every scan since it went
idle — and without it an upgrade would queue the user's entire history at once.

Autogenerate also proposed dropping ``ix_face_photos_embedding_hnsw``, because
that index exists only in migration ``20486507cf9d`` and not in ``models.py``
(the trap ``485f1296faf8`` records; see #162). Removed by hand: this revision
touches nothing on ``face_photos``.

Revision ID: c2d999801f26
Revises: a1f4c7d92b3e
Create Date: 2026-09-06 07:11:06.028562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d999801f26'
down_revision: Union[str, Sequence[str], None] = 'a1f4c7d92b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('consolidated_at', sa.DateTime(), nullable=True))
    op.add_column('conversations', sa.Column('consolidation_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('conversations', sa.Column('consolidation_next_retry_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    # ### end Alembic commands ###
    # Existing conversations count as consolidated as of their last change.
    op.execute("UPDATE conversations SET consolidated_at = updated_at WHERE updated_at IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_column('conversations', 'consolidation_next_retry_at')
    op.drop_column('conversations', 'consolidation_attempts')
    op.drop_column('conversations', 'consolidated_at')
    # ### end Alembic commands ###
