"""add_tool_kind_and_duration_to_messages

Revision ID: c4f16d4d97dd
Revises: 236f4ed54660
Create Date: 2026-09-27 19:56:13.903102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f16d4d97dd'
down_revision: Union[str, Sequence[str], None] = '236f4ed54660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('tool_kind', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('duration_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'duration_ms')
    op.drop_column('messages', 'tool_kind')
    # ### end Alembic commands ###
