name: Android Build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make gradlew executable
      run: chmod +x clients/KurisuAssistant/gradlew
      
    - name: Create secrets.properties
      run: |
        cd clients/KurisuAssistant
        echo "API_TOKEN=${{ secrets.API_TOKEN }}" > secrets.properties
        
    - name: Build with Gradle
      run: |
        cd clients/KurisuAssistant
        ./gradlew build
        
    - name: Run tests
      run: |
        cd clients/KurisuAssistant
        ./gradlew test
        
    - name: Build APK
      run: |
        cd clients/KurisuAssistant
        ./gradlew assembleDebug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kurisu-assistant-debug-apk
        path: clients/KurisuAssistant/app/build/outputs/apk/debug/*.apk